version: '3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: arsenal
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
    database_data: {}
